### ISSUE TITLE
Conflict with Domterion/catfetch

### ISSUE THREAD

**Issue by ThatOneCalculator** [JhonnyRice/cat-fetch#19]
There's actually already a fetch that uses the name `catfetch` (https://github.com/Domterion/catfetch), given this repo's name is `cat-fetch` and not `catfetch`, maybe the command name could be changed to `cat-fetch` too? (I like having a lot of fetches installed on my system)

**Comment by Francicoria** [comment]
while you are in the folder you cloned this repo do: `sudo cp catfetch /usr/bin/cat-fetch`
