### ISSUE TITLE
Parsing /etc/os-release for NAME

### ISSUE THREAD

**Issue by bpribula** [JhonnyRice/cat-fetch#21]
Hi,

When running catfetch on Slackware I get the following in the os field:

os: NAME=Slackware

instead of:

os: Slackware

The reason being is it's optional to quote values in /etc/os-release if they don't contain special characters and Slackware doesn't quote the NAME value.

Would it be possible to change:

OS=$(grep -m1 "NAME=" < /etc/os-release | cut -d '"' -f 2)

to this:

OS=$(grep -m1 "NAME=" < /etc/os-release | cut -d '"' -f 2 | _**cut -d '=' -f 2**_)

This way both formats are covered.

Thanks

**Comment by rice7th** [comment]
Thanks for pointing this out

**Comment by rice7th** [comment]
Fixed

**Comment by bpribula** [comment]
Sorry, I should've mentioned that the issue is with catfetchposix as well.
