### ISSUE TITLE
Apparently wrong URL on curl command, and Install from source freezing.

### ISSUE THREAD

**Issue by chloescaramal** [JhonnyRice/cat-fetch#6]
![image](https://user-images.githubusercontent.com/25325687/150641538-58759f56-ae5a-4cd0-9f79-9e5fa4c95de4.png)

When trying to install from source code (downloading the .zip and running ./install.sh) ir pretty much freezes here:
![image](https://user-images.githubusercontent.com/25325687/150641599-aa7aa61b-5736-405a-a891-ccfd821da910.png)

**Comment by rice7th** [comment]
hmmm

**Comment by rice7th** [comment]
Ok fixed

**Comment by chloescaramal** [comment]
> 

will try again :)
